version: "3.3"

services:
  mvn-db:
    image: aksw/rpt
    #environment:
      #USER_ID: "${USER_ID}"
      #GROUP_ID: "${GROUP_ID}"
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./data:/data
    working_dir: /
    command: integrate -X --server --db-engine tdb2 --db-loc /data --db-keep
    network_mode: "host"
    ports:
      - "7531:7351"  # Sync process
    restart: on-failure
  mvn-sync:
    # image: tenforce/virtuoso
    build:
      context: .
    environment:
      USER_ID: "${USER_ID}"
      GROUP_ID: "${GROUP_ID}"
    user: "${USER_ID}:${GROUP_ID}"
      # WORKDIR: /workdir
    volumes:
      # - ~/.m2/repository:/home/user/.m2/host-repository
      - ~/.m2/repository:/home/user/.m2/repository
      - ~/.m2/repository:/repository
      - ./target/repository:/home/user/.m2/cache-repository
      - ./settings.xml:/home/user/.m2/settings.xml
      - ./workdir:/workdir
      - ./resources:/home/user/mvn-sync/resources
      - ./prepublish:/home/user/mvn-sync/prepublish
    entrypoint: ["/home/user/mvn-sync/resources/run-dcat-mvn-sync.sh", "/repository", "/workdir"]
    network_mode: "host"
#    ports:
#      - "1111:1111"
#      - "8890:8890"
    restart: on-failure

