version: "3.3"

services:
  # Sync process
  mvn-sync:
    # image: tenforce/virtuoso
    build:
      context: .
    user: "${UID}:${GID}"
    environment:
      UID: "${UID}"
      GID: "${GID}"
      WORKDIR: /workdir
    volumes:
      # - ~/.m2/repository:/home/user/.m2/host-repository
      - ~/.m2/repository:/home/user/.m2/repository
      - ~/.m2/repository:/repository
      - ./target/repository:/home/user/.m2/cache-repository
      - ./settings.xml:/home/user/.m2/settings.xml
      - ./workdir:/workdir
    network_mode: "host"
#    ports:
#      - "1111:1111"
#      - "8890:8890"
    restart: on-failure

