PREFIX dcat: <http://www.w3.org/ns/dcat#>
CONSTRUCT {
 ?s a ?t
}
#SELECT ?s ?t
{
    {
      ?s dcat:distribution ?o
      FILTER(!EXISTS { ?s a dcat:Dataset })
      BIND(dcat:Dataset AS ?t)
    }
  UNION
    {
      ?s dcat:downloadURL ?o
      FILTER(!EXISTS { ?s a dcat:Distribution })
      BIND(dcat:Distribution AS ?t)
    }
}
