CONSTRUCT {

  ?s dcat:versionTag dcat:latestVersion

  # Below causes Virtuoso 22023 Error VECDT: SR066: Unsupported case in CONVERT (incomplete RDF box -> IRI_ID)
  # ?s dcat:versionTag latest"

  # The tp below breaks with virtuoso as it returns the boolean as an int,
  # causing a type cast exception Integer->Boolean *shrug*
  # ?s dcat:isLatestVersion true

  #  ?s a dcat:LatestVersion
  # Using a property other than rdf:type is better for faceted search
} {
    { SELECT DISTINCT ?s { ?s dcat:distribution ?x } }
  UNION  
    { SELECT DISTINCT ?s { ?s dcat:downloadURL ?x } }
  FILTER(NOT EXISTS { ?s owl:priorVersion ?x })
  
  # ?s ?p ?o
  #FILTER(?p = dcat:distribution || ?p = dcat:downloadURL)
}
