PREFIX dcat: <http://www.w3.org/ns/dcat#>
SELECT DISTINCT ?s
{
  { SELECT DISTINCT ?s {
      ?s ?p ?o
      FILTER(?p = dcat:distribution || ?p = dcat:downloadURL)
  } }
  OPTIONAL { ?s dcterms:identifier ?id }
  FILTER(REGEX(STR(?s), <env:ARG>, "i") || REGEX(STR(?id), <env:ARG>, "i"))

#  UNION
#    {
#      ?x dcat:downloadURL ?s
#      FILTER(REGEX(STR(?s), <env:ARG>, "i"))
#    }
#}

}

