PREFIX dcat: <http://www.w3.org/ns/dcat#>
SELECT ?s
{
    {
      ?s ?p ?o
      FILTER(?p = dcat:distribution || ?p = dcat:downloadURL)
      OPTIONAL {
        ?s dcterms:identifier ?id
      }

      FILTER(?s = <env://ARG> || ?id = <env:ARG>)
    }
   UNION
    {
      ?x dcat:downloadURL ?s
      FILTER(?s = <env://ARG>)
    }
}

